#! /usr/bin/bash
#title           :renameFilesByPattern
#description     :This script is to Rename files in a directory based on a pattern specified iteratively
#author		     :Ioannis Ioannidis
#date            :20/09/2016
#version         :1    
#usage			 : ./renameFilesByPattern filenamePart matchexpression replaceexpression" ex. to find files containing 'myframe' and change the myfr part to my_fr
#------------------------------------------------------------------------------------we would type: ./renameFilesByPattern myframe myfr my_fr
#date modified   :21/09/2016
#==============================================================================

#How to use the renameFilesByPattern script:
#
#1)open bash profile: geany ~/.bashrc
#2)append this line to the end: export PATH=$PATH:/public/bin/mpegScripts​
#3)Save and Close bash
#4)Source bash: source ~/.bashrc
#
#
#ex. to find and rename files containing 'myframe' and change the 'myfr' part to 'my_fr'
#we would type: 

#renameFilesByPattern myframe myfr my_fr​
#
#-1st argument myframe: common part of the name of the files we are trying to rename
#-2nd argument myf: part of file to be replaced by the 3rd argument
#-3rd argument my_f: part of file to replace the 2nd argument

#ex.  myframe.0001.tiff would become my_frame.0001.tiff


if [ $# -ne 3 ]; then
	echo $2
	echo "Basic usage syntax: ./renameScript commonFilenamePattern matchExpression replaceExpression"
	echo "Syntax usage explanation: to match all files in a directory containing the word 'frame', and replace the word 'fr' with '.fr' we would type: renameFilesByPattern frame fr .fr"
	
	echo "Please rerun using proper syntax!"
	exit
fi

PATTERNFILE=$1
PATTERNMATCHEXPR=$2
PATTERNREPLACEEXPR=$3

#echo $PATTERNFILE
#echo $PATTERNMATCHEXPR
#echo $PATTERNREPLACEEXPR

for f in *$PATTERNFILE*; do mv $f ${f/$PATTERNMATCHEXPR/$PATTERNREPLACEEXPR}; done


